# Breast Cancer Winsconsin

Features are computed from a digitized image of a fine needle aspirate (FNA) of a breast mass. They describe characteristics of the cell nuclei present in the image.
n the 3-dimensional space is that described in: [K. P. Bennett and O. L. Mangasarian: "Robust Linear Programming Discrimination of Two Linearly Inseparable Sets", Optimization Methods and Software 1, 1992, 23-34].

<hr />

In [15]:
import pandas as pd

data = pd.read_csv('./data/data.csv')
data.drop(columns=['id'], inplace=True)
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    str    
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null

In [16]:
data.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [17]:
resumen  = {
    'Cantidad de datos faltantes: ': data.isna().sum(),
    'Porcentaje de datos faltantes: ': data.isna().mean()
}

print('='*40)
print(resumen)
print('='*40)

{'Cantidad de datos faltantes: ': diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64, 'Porcentaje de datos faltantes: ': diagnosis         

In [18]:
data['diagnosis'].unique()

<StringArray>
['M', 'B']
Length: 2, dtype: str

In [19]:
print('='*40)
print('Numero de datos de categoria 1: ', len(data[data['diagnosis'] == 'M']))
print('Numero de datos de categoria 2: ', len(data[data['diagnosis'] != 'M']))

Numero de datos de categoria 1:  212
Numero de datos de categoria 2:  357


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
import numpy as np

data['diagnosis'] = np.where(data['diagnosis'] == 'M', 1,0)

x = data.drop(columns=['diagnosis'])
y = data['diagnosis']

x_train, x_test, y_train, y_test =train_test_split(x,y, test_size=0.8, random_state=777, shuffle=True, stratify=y)

In [22]:

from sklearn.svm import SVC, LinearSVC, NuSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier




## KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier


## Creacion del modelo
knn = KNeighborsClassifier(n_neighbors=8, n_jobs=-1)

## Entrenamiento y predicciones del modelo
knn.fit(x_train, y_train)
y_pred_knn = knn.predict(x_test)

## Cálculo de las métricas
acc_knn = accuracy_score(y_test, y_pred_knn)
prec_knn = precision_score(y_test, y_pred_knn)
rec_knn = recall_score(y_test, y_pred_knn)
f1_knn = f1_score(y_test, y_pred_knn)
cm_knn= confusion_matrix(y_test, y_pred_knn)

print("=" * 50)
print(" " * 10 + "REPORTE DE MÉTRICAS (KNN)")
print("=" * 50)
print(f"Accuracy        : {acc_knn:.4f}")
print(f"Precision       : {prec_knn:.4f}")
print(f"Recall          : {rec_knn:.4f}")
print(f"Puntuacion F1   : {f1_knn:.4f}")
print("-" * 50)
print("Matriz de Confusion:")
print(cm_knn)
print("=" * 50)

          REPORTE DE MÉTRICAS (KNN)
Accuracy        : 0.9189
Precision       : 0.9586
Recall          : 0.8176
Puntuacion F1   : 0.8825
--------------------------------------------------
Matriz de Confusion:
[[280   6]
 [ 31 139]]


## SVM's

In [28]:
from sklearn.svm import SVC, LinearSVC, NuSVC


# ==========================================
# 1. Support Vector Classification (SVC)
# ==========================================
svc = SVC() 
svc.fit(x_train, y_train)
y_pred_svc = svc.predict(x_test)

acc_svc = accuracy_score(y_test, y_pred_svc)
prec_svc = precision_score(y_test, y_pred_svc)
rec_svc = recall_score(y_test, y_pred_svc)
f1_svc = f1_score(y_test, y_pred_svc)
cm_svc = confusion_matrix(y_test, y_pred_svc)

print("=" * 50)
print(" " * 10 + "REPORTE DE MÉTRICAS (SVC)")
print("=" * 50)
print(f"Accuracy        : {acc_svc:.4f}")
print(f"Precision       : {prec_svc:.4f}")
print(f"Recall          : {rec_svc:.4f}")
print(f"Puntuacion F1   : {f1_svc:.4f}")
print("-" * 50)
print("Matriz de Confusion:")
print(cm_svc)
print("=" * 50)
print("\n")


# =========================================
# 2. Linear Support Vector Classification (LinearSVC)
# ==========================================
linear_svc = LinearSVC(dual=False) 
linear_svc.fit(x_train, y_train)
y_pred_linear_svc = linear_svc.predict(x_test)

acc_linear_svc = accuracy_score(y_test, y_pred_linear_svc)
prec_linear_svc = precision_score(y_test, y_pred_linear_svc)
rec_linear_svc = recall_score(y_test, y_pred_linear_svc)
f1_linear_svc = f1_score(y_test, y_pred_linear_svc)
cm_linear_svc = confusion_matrix(y_test, y_pred_linear_svc)

print("=" * 50)
print(" " * 10 + "REPORTE DE MÉTRICAS (LinearSVC)")
print("=" * 50)
print(f"Accuracy        : {acc_linear_svc:.4f}")
print(f"Precision       : {prec_linear_svc:.4f}")
print(f"Recall          : {rec_linear_svc:.4f}")
print(f"Puntuacion F1   : {f1_linear_svc:.4f}")
print("-" * 50)
print("Matriz de Confusion:")
print(cm_linear_svc)
print("=" * 50)
print("\n")


# ==========================================
# 3. Nu-Support Vector Classification (NuSVC)
# ==========================================
nu_svc = NuSVC() 
nu_svc.fit(x_train, y_train)
y_pred_nu_svc = nu_svc.predict(x_test)

acc_nu_svc = accuracy_score(y_test, y_pred_nu_svc)
prec_nu_svc = precision_score(y_test, y_pred_nu_svc)
rec_nu_svc = recall_score(y_test, y_pred_nu_svc)
f1_nu_svc = f1_score(y_test, y_pred_nu_svc)
cm_nu_svc = confusion_matrix(y_test, y_pred_nu_svc)

print("=" * 50)
print(" " * 10 + "REPORTE DE MÉTRICAS (NuSVC)")
print("=" * 50)
print(f"Accuracy        : {acc_nu_svc:.4f}")
print(f"Precision       : {prec_nu_svc:.4f}")
print(f"Recall          : {rec_nu_svc:.4f}")
print(f"Puntuacion F1   : {f1_nu_svc:.4f}")
print("-" * 50)
print("Matriz de Confusion:")
print(cm_nu_svc)
print("=" * 50)

          REPORTE DE MÉTRICAS (SVC)
Accuracy        : 0.8969
Precision       : 0.9843
Recall          : 0.7353
Puntuacion F1   : 0.8418
--------------------------------------------------
Matriz de Confusion:
[[284   2]
 [ 45 125]]


          REPORTE DE MÉTRICAS (LinearSVC)
Accuracy        : 0.9627
Precision       : 0.9693
Recall          : 0.9294
Puntuacion F1   : 0.9489
--------------------------------------------------
Matriz de Confusion:
[[281   5]
 [ 12 158]]


          REPORTE DE MÉTRICAS (NuSVC)
Accuracy        : 0.8860
Precision       : 0.9836
Recall          : 0.7059
Puntuacion F1   : 0.8219
--------------------------------------------------
Matriz de Confusion:
[[284   2]
 [ 50 120]]


## Decision Tree Classifier